FROM wikibase/wdqs-frontend:wmde.10
COPY templates /templates/
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY Logo_EU_knowledgegraph.svg /usr/share/nginx/html/logo.svg
COPY Logo_EU_knowledgegraph.svg /usr/share/nginx/html/logo-embed.svg
